name: Run Vitest Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout folder
        uses: actions/checkout@v3

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run tests
        working-directory: ./client
        run: npx vitest
      
      - name: Deploy to Vercel
        if: success()  # Only deploy if the tests pass
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}